# Generated by Django 4.2.7 on 2024-01-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='poster',
            field=models.ImageField(null=True, upload_to='poster'),
        ),
    ]
