# Generated by Django 4.2.7 on 2024-01-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_user_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
