# Generated by Django 4.2.7 on 2024-01-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_job_contact_alter_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
